# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

#import kraken_pb2 as kraken__pb2
from lib import kraken_pb2 as kraken__pb2


class KrakenServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessKrakenRequest = channel.unary_unary(
                '/kraken.KrakenService/ProcessKrakenRequest',
                request_serializer=kraken__pb2.KrakenRequest.SerializeToString,
                response_deserializer=kraken__pb2.KrakenResponse.FromString,
                )


class KrakenServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessKrakenRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KrakenServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessKrakenRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessKrakenRequest,
                    request_deserializer=kraken__pb2.KrakenRequest.FromString,
                    response_serializer=kraken__pb2.KrakenResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kraken.KrakenService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class KrakenService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessKrakenRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kraken.KrakenService/ProcessKrakenRequest',
            kraken__pb2.KrakenRequest.SerializeToString,
            kraken__pb2.KrakenResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
