version: "3.4"
services:
#  mongo:
#    container_name: mongo
#    hostname: mongo
#    image: mongo:4.4.2
#    ports:
#      - 27017:27017
#    volumes:
#      - $PWD/db/mongo:/data/db
#    restart: always
#  redis:
#    container_name: redis
#    hostname: redis 
#    image: redis:6.2.6-alpine
#    ports:
#      - "6379:6379"
#    volumes:
#      - "$PWD/db/redis:/data"
#    restart: always
  influx:
    container_name: influx
    hostname: influx 
    image: influxdb:2.7
    ports:
      - "8086:8086"
    volumes:
      - "$PWD/db/influx:/var/lib/influxdb2"
    restart: always